apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pg-volume
  labels:
    type: local
spec:
  storageClassName: standard
  resources:
    requests:
      storage: 10Gi
  accessModes:
    - ReadWriteOnce
